# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoSimple < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.1/todo-simple_Darwin_arm64.tar.gz"
      sha256 "5581b48fc92f4f031f5c26a6e81af666bed1458e22566bee9efe9040c704fc4d"

      def install
        bin.install "todo-simple"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.1/todo-simple_Darwin_x86_64.tar.gz"
      sha256 "b1479d8a86d9357dc23eac8254df0cdc140dd910711f0d0ce4ffa48a32cc9d82"

      def install
        bin.install "todo-simple"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.1/todo-simple_Linux_arm64.tar.gz"
      sha256 "a9967266142d89ac707ad1a8bfc2b9bd3d621dbcef524ded92baa3840912cc7f"

      def install
        bin.install "todo-simple"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.1/todo-simple_Linux_x86_64.tar.gz"
      sha256 "4228775392789904ddad4eb68306ae15f6a27e4c4650c9b05d64ca04defb3c78"

      def install
        bin.install "todo-simple"
      end
    end
  end
end
