# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TodoSimple < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.2/todo-simple_Darwin_arm64.tar.gz"
      sha256 "7bbbe08882a2a9f9408a57dae0945226ee83ac669dc9651fddf87b36270010cd"

      def install
        bin.install "todo-simple"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.2/todo-simple_Darwin_x86_64.tar.gz"
      sha256 "907f50dcdb4df1bad98aaa9a7ae1eff2c304f350930f8a317fd81fe90293a711"

      def install
        bin.install "todo-simple"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.2/todo-simple_Linux_arm64.tar.gz"
      sha256 "7b1caedd6f5461cee58c0e8d43e832b0066eb4c9afaa4eafee056c32e69d9187"

      def install
        bin.install "todo-simple"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ujiuji1259/todo-simple/releases/download/v0.1.2/todo-simple_Linux_x86_64.tar.gz"
      sha256 "2fb3b93bb55527631b41fdd2624c55c64dafc879751ca8c78593550e626c20a1"

      def install
        bin.install "todo-simple"
      end
    end
  end
end
